# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.13.0

    - name: Cache dependencies
      uses: actions/cache@v2
      id: gem-cache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-

    - name: Cache node modules
      uses: actions/cache@v2
      id: node-cache
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install gem dependencies
      if: steps.gem-cache.outputs.cache-hit != 'true'
      run: |
        bundle install

    - name: Install npm dependencies
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: |
        yarn install

    - name: Compilation assets with Webpack
      run: NODE_ENV=test bundle exec rails webpacker:compile

    - name: Run tests
      run: bundle exec rake
